version: '3.8'

services:
  app:
    build: .
    hostname: app
    restart: always
    volumes:
      - ./src:/opt/indieweb/src:rw
      - ./data:/opt/indieweb/data:rw
      - ./tests:/opt/indieweb/tests:rw
    networks:
      - iwinternal
    ports:
      - 89:8000
networks:
  iwinternal:
    driver: bridge